apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  restartPolicy: Never
  volumes:
    - name: scratch
      emptyDir: {}
    - name: mydir
      hostPath:
        path: /home/yourusername/models/ddp_mnist/1.15.1
        type: Directory
  containers:
    - name: gaudi-container
      image: vault.habana.ai/gaudi-docker/1.15.1/ubuntu22.04/habanalabs/pytorch-installer-2.2.0:latest
      volumeMounts:
        - mountPath: /scratch
          name: scratch
        - mountPath: /mydir
          name: mydir 
      resources:
        limits:
          memory: 32G
          cpu: 12
          habana.ai/gaudi: 1
          hugepages-2Mi: 95000Mi
        requests:
          memory: 32G
          cpu: 12
          habana.ai/gaudi: 1
          hugepages-2Mi: 95000Mi
      command: ["/bin/sh","-c"]
      args:
        - hl-smi;
          export HOME=/scratch/tmp;
          export PATH=/scratch/tmp/.local/bin:$PATH;
          cd /mydir;
          python mnist_onecard.py --epochs 20 --target-accuracy 0.90;

         

