apiVersion: v1
kind: Pod
metadata:
  name: mnist
  namespace: yournamespace
spec:
  restartPolicy: Never
  volumes:
    - name: scratch
      emptyDir: {}
    - name: mydir
      hostPath:
        path: /home/yourfolder
        type: Directory
  containers:
    - name: gaudi-container
      image: vault.habana.ai/gaudi-docker/1.21.4/ubuntu22.04/habanalabs/pytorch-installer-2.6.0:latest
      volumeMounts:
        - mountPath: /scratch
          name: scratch
        - mountPath: /mydir
          name: mydir 
      resources:
        limits:
          memory: 32G
          cpu: 12
          habana.ai/gaudi: 1
          hugepages-2Mi: 30000Mi
        requests:
          memory: 32G
          cpu: 12
          habana.ai/gaudi: 1
          hugepages-2Mi: 30000Mi
      command: ["/bin/sh","-c"]
      args:
        - hl-smi;
          cd /mydir;
          python mnist_onecard.py --epochs 20 --target-accuracy 0.90;

         

