apiVersion: v1
kind: Pod
metadata:
  name: resnext101
  namespace: yourusername-restricted
spec:
  restartPolicy: Never
  volumes:
    - name: scratch
      emptyDir: {}
    - name: dataset
      hostPath:
        path: /voyager/ceph/users/yourusername/datasets/imagenet/ILSVRC2012
        type: Directory
    - name: output
      hostPath:
        path: /voyager/ceph/users/yourusername/results/resnet/resnext101/1card
        type: Directory
  hostIPC: true
  containers:
    - name: gaudi-container
      image: vault.habana.ai/gaudi-docker/1.21.4/ubuntu22.04/habanalabs/pytorch-installer-2.6.0:latest
      volumeMounts:
        - mountPath: /scratch
          name: scratch
        - mountPath: /dataset
          name: dataset
        - mountPath: /output
          name: output
      resources:
        limits:
          memory: 32G
          cpu: 12
          habana.ai/gaudi: 1
          hugepages-2Mi: 30000Mi
        requests:
          memory: 32G
          cpu: 12
          habana.ai/gaudi: 1
          hugepages-2Mi: 30000Mi
      command: ["/bin/sh","-c"]
      args:
        - >-
          hl-smi;
          export HOME=/scratch/tmp;
          cd /scratch;
          mkdir -p tmp;
          git clone -b 1.21.0 https://github.com/HabanaAI/Model-References;
          cd Model-References/PyTorch/computer_vision/classification/torchvision;
          export PYTHONPATH=/scratch/Model-References:$PYTHONPATH;
          export PT_HPU_EAGER_ENABLE_GRADIENT_VIEW_LAYOUT_OPT=1;
          pip install -r requirements.txt;
          python3 -u train.py \
                  --dl-worker-type="HABANA" --batch-size 256 \
                  --model resnext101_32x4d --device hpu --workers 8 \
                  --print-freq 20 --dl-time-exclude False \
                  --deterministic \
                  --data-path /dataset \
                  --output-dir /output  \
                  --epochs 1 --autocast \
                  --lr 0.1 --custom-lr-values 0.1 0.01 0.001 0.0001 \
                  --custom-lr-milestones 0 30 60 80 \
                  --run-lazy-mode=False --use_torch_compile ;
  
