apiVersion: v1
kind: Pod
metadata:
  name: resnet50
  namespace: yourusername-restricted
spec:
  restartPolicy: Never
  volumes:
    - name: scratch
      emptyDir: {}
    - name: dataset
      hostPath:
        path: /voyager/ceph/users/yourusername/datasets/imagenet/ILSVRC2012
        type: Directory
    - name: output
      hostPath:
        path: /voyager/ceph/users/yourusername/results/resnet/resnet50/1card
        type: Directory
  hostIPC: true
  containers:
    - name: gaudi-container
      image: vault.habana.ai/gaudi-docker/1.21.4/ubuntu22.04/habanalabs/pytorch-installer-2.6.0:latest
      #image: vault.habana.ai/gaudi-docker/1.15.1/ubuntu22.04/habanalabs/pytorch-installer-2.2.0:latest
      volumeMounts:
        - mountPath: /scratch
          name: scratch
        - mountPath: /dataset
          name: dataset
        - mountPath: /output
          name: output
      resources:
        limits:
          memory: 32G
          cpu: 12
          habana.ai/gaudi: 1
          hugepages-2Mi: 30000Mi
        requests:
          memory: 32G
          cpu: 12
          habana.ai/gaudi: 1
          hugepages-2Mi: 30000Mi
      command: ["/bin/sh","-c"]
      args:
        - >-
          hl-smi;
          export HOME=/scratch/tmp;
          cd /scratch;
          mkdir -p tmp;
          git clone -b 1.21.0 https://github.com/HabanaAI/Model-References;
          cd Model-References/PyTorch/computer_vision/classification/torchvision;
          export PYTHONPATH=/scratch/Model-References:$PYTHONPATH;
          export PT_HPU_EAGER_ENABLE_GRADIENT_VIEW_LAYOUT_OPT=1;
          pip install -r requirements.txt;
          python3 -u train.py \
                  --dl-worker-type="HABANA" --batch-size 256 \
                  --model resnet50 --device hpu --workers 8 \
                  --print-freq 20 --dl-time-exclude False \
                  --data-path /dataset \
                  --output-dir /output  \
                  --epochs 1 --autocast \
                  --optimizer=lars -eoe 3 -ebe 4 \
                  --lars_base_learning_rate 2.5 \
                  --label-smoothing=0.1 \
                  --run-lazy-mode=False --use_torch_compile ;
  
