apiVersion: v1
kind: Pod
metadata:
  name: unet2d
spec:
  restartPolicy: Never
  volumes:
    - name: scratch
      emptyDir: {}
    - name: ceph
      hostPath:
        path: /voyager/ceph/users/javierhn
        type: Directory
  containers:
    - name: gaudi-container
      image: vault.habana.ai/gaudi-docker/1.11.0/ubuntu22.04/habanalabs/tensorflow-installer-tf-cpu-2.12.1:latest
      volumeMounts:
        - mountPath: /scratch
          name: scratch
        - mountPath: /ceph
          name: ceph 
      resources:
        limits:
          memory: 32G
          cpu: 6
          habana.ai/gaudi: 1
          hugepages-2Mi: 95000Mi
        requests:
          memory: 32G
          cpu: 6
          habana.ai/gaudi: 1
          hugepages-2Mi: 95000Mi
      env:
        - name: dataset
          value: "/ceph/datasets/UNet2D_tf"
        - name: out
          value: "/ceph/results/unet2d_tf"
      command: ["/bin/sh","-c"]
      args:
         - hl-smi;
           export HOME=/scratch/tmp/javierhn;
           cd /scratch;
           mkdir -p tmp/javierhn;
           git clone -b 1.11.0 https://github.com/HabanaAI/Model-References;
           export PYTHONPATH=$PYTHONPATH:/scratch/Model-References/;
           cd /scratch/Model-References/TensorFlow/computer_vision/Unet2D;
           python3 -m pip install -r requirements.txt;
           python3 unet2d.py --data_dir ${dataset} --batch_size 8 --dtype bf16 --model_dir ${out} --fold 0 --tensorboard_logging;
