apiVersion: v1
kind: Pod
metadata:
  name: data
spec:
  restartPolicy: Never
  nodeSelector:
    brightcomputing.com/node-category: 'compute'
  volumes:
    - name: scratch
      emptyDir: {}
    - name: dataset
      hostPath:
        path: /voyager/ceph/users/youruser/datasets/COCO
        type: Directory
  containers:
    - name: compute-container
      image: vault.habana.ai/gaudi-docker/1.11.0/ubuntu22.04/habanalabs/pytorch-installer-2.0.1:latest
      volumeMounts:
        - mountPath: /scratch
          name: scratch
        - mountPath: /dataset
          name: dataset 
      resources:
        limits:
          memory: 368G
          cpu: 104
        requests:
          memory: 32G
          cpu: 12
      command: ["/bin/sh","-c"]
      args:
        - >-
            hl-smi;
            cd /dataset;
            curl -O http://images.cocodataset.org/zips/train2017.zip;
            unzip train2017.zip;
            curl -O http://images.cocodataset.org/zips/val2017.zip;
            unzip val2017.zip;
            curl -O http://images.cocodataset.org/annotations/annotations_trainval2017.zip;
            unzip annotations_trainval2017.zip;

