apiVersion: v1
kind: Pod
metadata:
  name: ssd
  namespace: yourusername-restricted
spec:
  restartPolicy: Never
  volumes:
    - name: scratch
      emptyDir: {}
    - name: dataset
      hostPath:
        path: /voyager/ceph/users/yourusername/datasets/COCO
        type: Directory
    - name: pretrained
      hostPath:
        path: /voyager/ceph/users/yourusername/datasets/ssd_pretrained_weights
        type: Directory
  hostIPC: true
  containers:
    - name: gaudi-container
      image: vault.habana.ai/gaudi-docker/1.21.4/ubuntu22.04/habanalabs/pytorch-installer-2.6.0:latest
      volumeMounts:
        - mountPath: /scratch
          name: scratch
        - mountPath: /dataset
          name: dataset
        - mountPath: /pretrained
          name: pretrained
      resources:
        limits:
          memory: 256G
          cpu: 94
          habana.ai/gaudi: 8
          hugepages-2Mi: 30000Mi
        requests:
          memory: 256G
          cpu: 94
          habana.ai/gaudi: 8
          hugepages-2Mi: 30000Mi
          #env:
          #- name: dataset
          #value: "/ceph/datasets/bloom/checkpoints"
      command: ["/bin/sh","-c"]
      args:
        - >-
           hl-smi;
           export HOME=/scratch/tmp;
           export PATH=/scratch/tmp/.local/bin:$PATH;

           export PYTHONPATH=/scratch/Model-References:$PYTHONPATH;

           mkdir -p /scratch/tmp/;
           cd /scratch;
           export N_CARDS=8;
           git clone -b 1.19.0 https://github.com/HabanaAI/Model-References;

           cd Model-References/PyTorch/computer_vision/detection/mlcommons/SSD;
           pip install -r requirements.txt;

           export PT_HPU_LAZY_MODE=1;

           export CMD="python ssd/train.py \
                  --batch-size 128 \
                  --num-workers 12 \
                  --epochs 50 \
                  --log-interval 100 \
                  --val-interval 5 \
                  --data /dataset \
                  --pretrained-backbone /pretrained/resnet34-333f7ec4.pth \
                  --use-hpu \
                  --hpu-lazy-mode \
                  --autocast";

           mpirun -n ${N_CARDS} \
                    --allow-run-as-root \
                    --bind-to core \
                    --map-by ppr:4:socket:PE=6 \
                    -rank-by core --report-bindings \
                    --tag-output \
                    --merge-stderr-to-stdout \
                    -x PYTHONPATH \
                    -x PT_HPU_LAZY_MODE \
                    $CMD;



