apiVersion: v1
kind: Pod
metadata:
        name: helloworld
spec:
        restartPolicy: Never
        containers:
                - name: gaudi-container
                  image: vault.habana.ai/gaudi-docker/1.11.0/ubuntu22.04/habanalabs/tensorflow-installer-tf-cpu-2.12.1:latest
                  resources:
                         limits:
                                memory: 1G
                                cpu: 1
                                habana.ai/gaudi: 1
                         requests:
                                memory: 1G
                                cpu: 1
                                habana.ai/gaudi: 1
                  command: ["/bin/sh","-c"]
                  args: ["echo Hello World!"]
