apiVersion: v1
kind: Pod
metadata:
  name: diffusers
spec:
  restartPolicy: Never
  volumes:
    - name: scratch
      emptyDir: {}
    - name: workdir
      hostPath:
        path: /home/yourusername/models/huggingface/diffusers/commoncanvas
        type: Directory
    - name: dataset
      hostPath:
        path: /voyager/ceph/users/yourusername/datasets/huggingface
        type: Directory
  containers:
    - name: gaudi-container
      image: vault.habana.ai/gaudi-docker/1.15.1/ubuntu22.04/habanalabs/pytorch-installer-2.2.0:latest
      volumeMounts:
        - mountPath: /scratch
          name: scratch
        - mountPath: /workdir
          name: workdir 
        - mountPath: /dataset
          name: dataset 
      resources:
        limits:
          memory: 32G
          cpu: 12
          habana.ai/gaudi: 1
          hugepages-2Mi: 95000Mi
        requests:
          memory: 32G
          cpu: 12
          habana.ai/gaudi: 1
          hugepages-2Mi: 95000Mi
      command: ["/bin/sh","-c"]
      args:
        - hl-smi;
          cd /workdir;
          pip install -r requirements.txt;
          python commoncanvas-xl.py;
         

