apiVersion: v1
kind: Pod
metadata:
  name: data-down
spec:
  restartPolicy: Never
  volumes:
    - name: scratch
      emptyDir: {}
    - name: dataset
      hostPath:
        path: /voyager/ceph/users/yourusername/datasets/huggingface
        type: Directory
  containers:
    - name: gaudi-container
      image: vault.habana.ai/gaudi-docker/1.15.1/ubuntu22.04/habanalabs/pytorch-installer-2.2.0:latest
      #      image: vault.habana.ai/gaudi-docker/1.11.0/ubuntu22.04/habanalabs/pytorch-installer-2.0.1:latest
      volumeMounts:
        - mountPath: /scratch
          name: scratch
        - mountPath: /dataset
          name: dataset
      resources:
        limits:
          memory: 32G
          cpu: 12
          habana.ai/gaudi: 1
          #hugepages-2Mi: 95000Mi
        requests:
          memory: 32G
          cpu: 12
          habana.ai/gaudi: 1
          #hugepages-2Mi: 95000Mi
          #env:
          #- name: dataset
          #value: "/ceph/datasets/bloom/checkpoints"
      command: ["/bin/sh","-c"]
      args:
        - >-
           hl-smi;
           export HOME=/scratch/tmp;
           export PATH=$PATH:$HOME;

           mkdir -p /$HOME;
           cd /scratch;
           wget https://github.com/git-lfs/git-lfs/releases/download/v3.2.0/git-lfs-linux-amd64-v3.2.0.tar.gz;
           tar -xvf git-lfs*;
           cd git-lfs*;
           install git-lfs $HOME/git-lfs;
           echo 'Git-lfs installed!';

           cd /dataset;
           git lfs install;
           git clone https://huggingface.co/common-canvas/CommonCanvas-XL-C ;
