apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: javierhn-resnet-16cards
  namespace: default
spec:
  slotsPerWorker: 8
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          volumes:
            - name: mydir
              hostPath:
                path: /home/javierhn
                type: Directory
            - name: scratch
              emptyDir: {}
            - name: ceph
              hostPath:
                path: /voyager/ceph/users/javierhn
                type: Directory
          hostIPC: true
          containers:
            - image: vault.habana.ai/gaudi-docker/1.11.0/ubuntu22.04/habanalabs/pytorch-installer-2.0.1:latest
              name: resnet-launcher
              volumeMounts:
                - name: mydir
                  mountPath: /home
                - name: scratch
                  mountPath: /scratch
                - name: ceph
                  mountPath: /ceph
              env:
                - name: dataset
                  value: "/ceph/datasets/imagenet/ILSVRC2012"
                - name: output
                  value: "/ceph/results/resnet/resnet50/16cards"
              command: ["/bin/bash", "-c"]
              args:
                - >-
                  hl-smi;
                  declare -xr HOME='/scratch/tmp';
                  declare -xr NUM_NODES=2;
                  declare -xr NGPU_PER_NODE=8;
                  declare -xr N_CARDS=$((NUM_NODES*NGPU_PER_NODE));

                  declare -xr RUN_PATH=/home/models/resnet/16cards;
                  declare -xr MODEL_PATH=/scratch/Model-References/PyTorch/computer_vision/classification/torchvision;

                  declare -xr PYTHONPATH=$PYTHONPATH:/scratch/Model-References;

                  HOSTSFILE=${HOSTSFILE:-$OMPI_MCA_orte_default_hostfile};
                  declare -xr MASTER_ADDR=$(head -n 1 $HOSTSFILE | sed -n s/[[:space:]]slots.*//p);
                  declare -xr MASTER_PORT=${MASTER_PORT:-15566};

                  echo $MASTER_ADDR;
                  echo $MASTER_PORT;

                  mpirun  --npernode 1 \
                    --tag-output \
                    --allow-run-as-root \
                    --prefix $MPI_ROOT \
                    -x MODEL_PATH \
                    -x HOME \
                    $RUN_PATH/setup.sh;

                  declare -xr CMD="python3 $MODEL_PATH/train.py \
                                   --batch-size 256 \
                                   --model resnet50 \
                                   --device hpu \
                                   --print-freq 1 \
                                   --dl-time-exclude False \
                                   --deterministic \
                                   --data-path ${dataset} \
                                   --output-dir ${output} \
                                   --save-checkpoint \
                                   --epochs 1 \
                                   --autocast  \
                                   --lr 0.1 \
                                   --custom-lr-values 0.275 0.45 0.625 0.8 0.08 0.008 0.0008 \
                                   --custom-lr-milestones 1 2 3 4 30 60 80 ";



                  mpirun -np ${N_CARDS} \
                    --allow-run-as-root \
                    --bind-to core \
                    --map-by ppr:4:socket:PE=6 \
                    -rank-by core --report-bindings \
                    --tag-output \
                    --merge-stderr-to-stdout --prefix $MPI_ROOT \
                    -x MASTER_ADDR=$MASTER_ADDR \
                    -x MASTER_PORT=$MASTER_PORT \
                    -x PYTHONPATH \
                    -x HOME \
                    $CMD;

    Worker:
      replicas: 2
      template:
        spec:
          volumes:
            - name: mydir
              hostPath:
                path: /home/javierhn
                type: Directory
            - name: scratch
              emptyDir: {}
            - name: ceph
              hostPath:
                path: /voyager/ceph/users/javierhn
                type: Directory
          hostIPC: true
          containers:
            - image: vault.habana.ai/gaudi-docker/1.11.0/ubuntu22.04/habanalabs/pytorch-installer-2.0.1:latest
              name: resnet50-worker
              imagePullPolicy: Always
              resources:
                limits:
                  habana.ai/gaudi: 8
                  cpu: 95
                  memory: 409Gi
                  hugepages-2Mi: 95000Mi
                requests:
                  habana.ai/gaudi: 8
                  cpu: 95
                  memory: 409Gi
                  hugepages-2Mi: 95000Mi
              volumeMounts:
                - name: mydir
                  mountPath: /home
                - name: scratch
                  mountPath: /scratch
                - name: ceph
                  mountPath: /ceph
 
