apiVersion: v1
kind: Pod
metadata:
        name: pretrain
spec:
        restartPolicy: Never
        volumes:
               - name: scratch
                 emptyDir: {}
               - name: ceph
                 hostPath:
                        path: /voyager/ceph/users/yourusername
                        type: Directory
        containers:
                - name: gaudi-container
                  image: vault.habana.ai/gaudi-docker/1.11.0/ubuntu22.04/habanalabs/tensorflow-installer-tf-cpu-2.12.1:latest
                  volumeMounts:
                         - mountPath: /scratch
                           name: scratch
                         - mountPath: /ceph
                           name: ceph 
                  resources:
                         limits:
                                memory: 32G
                                cpu: 6
                                habana.ai/gaudi: 1
                                hugepages-2Mi: 95000Mi
                         requests:
                                memory: 32G
                                cpu: 6
                                habana.ai/gaudi: 1
                                hugepages-2Mi: 95000Mi
                  env:
                    - name: output
                      value: "/ceph/datasets/bert/pretrained/wwm_uncased_L-24_H-1024_A-16/"
                  command: ["/bin/sh","-c"]
                  args:
                    - hl-smi;
                      export HOME=/scratch/tmp;
                      cd /scratch;
                      mkdir -p tmp;
                      git clone -b 1.11.0 https://github.com/HabanaAI/Model-References;
                      cd Model-References/TensorFlow/nlp/bert/;
                      export PYTHONPATH=./:../../common:../../:../../../central/:$PYTHONPATH;
                      python3 download/download_pretrained_model.py "https://storage.googleapis.com/bert_models/2019_05_30/"  "wwm_uncased_L-24_H-1024_A-16"  True;
                      cp -r wwm_uncased_L-24_H-1024_A-16 ${output};
