apiVersion: v1
kind: Pod
metadata:
        name: datagen
spec:
        restartPolicy: Never
        volumes:
               - name: scratch
                 emptyDir: {}
               - name: ceph
                 hostPath:
                        path: /voyager/ceph/users/javierhn
                        type: Directory
        containers:
                - name: gaudi-container
                  image: vault.habana.ai/gaudi-docker/1.11.0/ubuntu22.04/habanalabs/tensorflow-installer-tf-cpu-2.12.1:latest
                  volumeMounts:
                         - mountPath: /scratch
                           name: scratch
                         - mountPath: /ceph
                           name: ceph 
                  resources:
                         limits:
                                memory: 32G
                                cpu: 6
                                habana.ai/gaudi: 1
                                hugepages-2Mi: 95000Mi
                         requests:
                                memory: 32G
                                cpu: 6
                                habana.ai/gaudi: 1
                                hugepages-2Mi: 95000Mi
                  env:
                    - name: dataset
                      value: "/ceph/datasets/imagenet/ILSVRC2012"
                  command: ["/bin/sh","-c"]
                  args:
                    - hl-smi;
                      export HOME=/scratch/tmp;
                      cd /scratch;
                      mkdir -p tmp;
                      git clone -b 1.11.0 https://github.com/HabanaAI/Model-References;
                      export PYTHONPATH=$PYTHONPATH:/scratch/Model-References/;
                      cd /scratch/Model-References/TensorFlow/computer_vision/Resnets/resnet_keras;
                      python3 -m pip install -r requirements.txt;

                      cd ${dataset};
                      tar -xf ILSVRC2012_img_val.tar -C $dataset/validation;

                      wget -O synset_labels.txt https://raw.githubusercontent.com/tensorflow/models/master/research/slim/datasets/imagenet_2012_validation_synset_labels.txt;

                      cd /scratch/Model-References/TensorFlow/computer_vision/Resnets;
                      python3 preprocess_imagenet.py --raw_data_dir=${dataset} --local_scratch_dir=${dataset}/tf_records;
