apiVersion: v1
kind: Pod
metadata:
  name: datagen
spec:
  restartPolicy: Never
  volumes:
    - name: scratch
      emptyDir: {}
    - name: ceph
      hostPath:
        path: /voyager/ceph/users/youruser
        type: Directory
  containers:
    - name: gaudi-container
      image: vault.habana.ai/gaudi-docker/1.11.0/ubuntu22.04/habanalabs/pytorch-installer-2.0.1:latest
      volumeMounts:
        - mountPath: /scratch
          name: scratch
        - mountPath: /ceph
          name: ceph 
      resources:
        limits:
          memory: 32G
          cpu: 12
          habana.ai/gaudi: 1
          hugepages-2Mi: 95000Mi
        requests:
          memory: 32G
          cpu: 12
          habana.ai/gaudi: 1
          hugepages-2Mi: 95000Mi
      env:
        - name: dataset
          value: "/ceph/datasets/bloom/checkpoints"
      command: ["/bin/sh","-c"]
      args:
        - hl-smi;
          export HOME=/scratch/tmp;
          export PYTHONPATH=/scratch/Model-References:$PYTHONPATH;
          mkdir -p /scratch/tmp/;
          cd /scratch;
          git clone -b 1.11.0 https://github.com/HabanaAI/Model-References;
          cd Model-References/PyTorch/nlp/bloom;
          python3 -m pip install -r requirements.txt;
          python3 utils/fetch_weights.py --model bigscience/bloom-3b --weights ${dataset};
         

