apiVersion: v1
kind: Pod
metadata:
  name: mnist-8cards
  namespace: yourusername-sds275
spec:
  volumes:
    - name: scratch
      emptyDir: {}
    - name: mydir
      hostPath:
        path: /home/yourusername/models/ddp_mnist/1.21.4
        type: Directory
  hostIPC: true
  containers:
    - name: gaudi-container
      image: vault.habana.ai/gaudi-docker/1.21.4/ubuntu22.04/habanalabs/pytorch-installer-2.6.0:latest
      volumeMounts:
        - mountPath: /scratch
          name: scratch
        - mountPath: /mydir
          name: mydir 
      resources:
        limits:
          memory: 128G
          cpu: 94
          habana.ai/gaudi: 8
          hugepages-2Mi: 30000Mi
        requests:
          memory: 128G
          cpu: 94
          habana.ai/gaudi: 8
          hugepages-2Mi: 30000Mi
      command: ["/bin/sh","-c"]
      args:
        - >-
           hl-smi;
           export N_CARDS=8;
           export HOME=/scratch/tmp;
           export PATH=/scratch/tmp/.local/bin:$PATH;
           export RUN_PATH=/mydir;
           export PT_HPU_LAZY_MODE=1;
           cd /mydir;

           export CMD="python3 $RUN_PATH/mnist_multicard.py \
                       --epochs 10 \
                       --target-accuracy 0.89";
           mpirun -n $N_CARDS --bind-to core --map-by socket:PE=6 --rank-by core --report-bindings --allow-run-as-root  $CMD;
           sleep 200s; 

