apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: yourusername-unet3d-8cards
  namespace: yourusername-restricted
spec:
  slotsPerWorker: 8
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          nodeSelector:
            brightcomputing.com/node-category: 'compute'
          serviceAccountName: yourusername
          volumes:
            - name: mydir
              hostPath:
                path: /home/yourusername/models/voyager/unet_pytorch/1.15.1
                type: Directory
            - name: scratch
              emptyDir: {}
            - name: dataset
              hostPath:
                path: /voyager/ceph/users/yourusername/datasets/BraTS/pytorch/unet/01_3d
                type: Directory
            - name: output
              hostPath:
                path: /voyager/ceph/users/yourusername/results/unet_pytorch/3d/fold_0
                type: Directory
          hostIPC: true
          containers:
            - image: vault.habana.ai/gaudi-docker/1.15.1/ubuntu22.04/habanalabs/pytorch-installer-2.2.0:latest
              name: unet-launcher
              resources:
                requests:
                  cpu: 2
                  memory: 4Gi
                limits:
                  cpu: 4
                  memory: 8Gi
              volumeMounts:
                - name: mydir
                  mountPath: /mydir
                - name: scratch
                  mountPath: /scratch
                - name: dataset
                  mountPath: /dataset
                - name: output
                  mountPath: /output
              command: ["/bin/bash", "-c"]
              args:
                - >-
                  declare -xr NUM_NODES=1;
                  declare -xr NGPU_PER_NODE=8;
                  declare -xr N_CARDS=$((NUM_NODES*NGPU_PER_NODE));

                  declare -xr SYNAPSE_AI_VER=1.15.1;
                  declare -xr RUN_PATH=/mydir;
                  declare -xr MODEL_PATH=/scratch/Model-References/PyTorch/computer_vision/segmentation/Unet;

                  declare -xr PYTHONPATH=$PYTHONPATH:/scratch/Model-References;

                  HOSTSFILE=${HOSTSFILE:-$OMPI_MCA_orte_default_hostfile};
                  declare -xr MASTER_ADDR=$(head -n 1 $HOSTSFILE | sed -n s/[[:space:]]slots.*//p);
                  declare -xr MASTER_PORT=${MASTER_PORT:-15566};

                  echo $MASTER_ADDR;
                  echo $MASTER_PORT;

                  sleep 15s;

                  mpirun  --npernode 1 \
                    --tag-output \
                    --allow-run-as-root \
                    --prefix $MPI_ROOT \
                    -x MODEL_PATH \
                    -x SYNAPSE_AI_VER \
                    $RUN_PATH/setup.sh;


                  mpirun -npernode 1 \
                    -n ${NUM_NODES} \
                    --allow-run-as-root \
                    --bind-to none \
                    --report-bindings \
                    --tag-output \
                    --merge-stderr-to-stdout --prefix $MPI_ROOT \
                    -x MASTER_ADDR=$MASTER_ADDR \
                    -x MASTER_PORT=$MASTER_PORT \
                    -x MODEL_PATH \
                    -x PYTHONPATH \
                    -x N_CARDS \
                    $RUN_PATH/run_unet3d.sh;


    Worker:
      replicas: 1
      template:
        spec:
          serviceAccountName: yourusername
          volumes:
            - name: mydir
              hostPath:
                path: /home/yourusername/models/voyager/unet_pytorch/1.15.1
                type: Directory
            - name: scratch
              emptyDir: {}
            - name: dataset
              hostPath:
                path: /voyager/ceph/users/yourusername/datasets/BraTS/pytorch/unet/01_3d
                type: Directory
            - name: output
              hostPath:
                path: /voyager/ceph/users/yourusername/results/unet_pytorch/3d/fold_0
                type: Directory
          hostIPC: true
          containers:
            - image: vault.habana.ai/gaudi-docker/1.15.1/ubuntu22.04/habanalabs/pytorch-installer-2.2.0:latest
              name: unet-worker
              imagePullPolicy: Always
              resources:
                limits:
                  habana.ai/gaudi: 8
                  cpu: 95
                  memory: 409Gi
                  hugepages-2Mi: 95000Mi
                requests:
                  habana.ai/gaudi: 8
                  cpu: 95
                  memory: 409Gi
                  hugepages-2Mi: 95000Mi
              volumeMounts:
                - name: mydir
                  mountPath: /mydir
                - name: scratch
                  mountPath: /scratch
                - name: dataset
                  mountPath: /dataset
                - name: output
                  mountPath: /output

