apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: yourusername-test-16cards
  namespace: yourusername-restricted
spec:
  slotsPerWorker: 8
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          nodeSelector:
            brightcomputing.com/node-category: 'compute'
          serviceAccountName: yourusername
          volumes:
            - name: mydir
              hostPath:
                path: /home/yourusername/test_mpi/pytorch
                type: Directory
            - name: scratch
              emptyDir: {}
          hostIPC: true
          containers:
            - image: vault.habana.ai/gaudi-docker/1.15.1/ubuntu22.04/habanalabs/pytorch-installer-2.2.0:latest
              name: test-launcher
              resources:
                requests:
                  cpu: 2
                  memory: 4Gi
                limits:
                  cpu: 4
                  memory: 8Gi
              volumeMounts:
                - name: mydir
                  mountPath: /mydir
                - name: scratch
                  mountPath: /scratch
              command: ["/bin/bash", "-c"]
              args:
                - >-
                  declare -xr NUM_NODES=2;
                  declare -xr NGPU_PER_NODE=8;
                  declare -xr N_CARDS=$((NUM_NODES*NGPU_PER_NODE));

                  declare -xr SYNAPSE_AI_VER=1.15.1;
                  declare -xr RUN_PATH=/mydir;

                  declare -xr MODEL_PATH=/scratch/Model-References/PyTorch/examples/computer_vision/hello_world   ;
                  declare -xr PYTHONPATH=$PYTHONPATH:/scratch/Model-References;

                  HOSTSFILE=${HOSTSFILE:-$OMPI_MCA_orte_default_hostfile};
                  declare -xr MASTER_ADDR=$(head -n 1 $HOSTSFILE | sed -n s/[[:space:]]slots.*//p);
                  declare -xr MASTER_PORT=${MASTER_PORT:-15566};

                  echo $MASTER_ADDR;
                  echo $MASTER_PORT;

                  sleep 15s;

                  mpirun  --npernode 1 \
                    --tag-output \
                    --allow-run-as-root \
                    --prefix $MPI_ROOT \
                    -x MODEL_PATH \
                    -x SYNAPSE_AI_VER \
                    $RUN_PATH/setup.sh;

                  declare -xr CMD="python3 $MODEL_PATH/mnist.py \
                                   --batch-size=64 \
                                   --epochs=1 \
                                   --lr=1.0 \
                                   --gamma=0.7 \
                                   --hpu
                                   --autocast";

                  mpirun -np ${N_CARDS} \
                    --allow-run-as-root \
                    --bind-to core \
                    --map-by ppr:4:socket:PE=6 \
                    -rank-by core --report-bindings \
                    --tag-output \
                    --merge-stderr-to-stdout --prefix $MPI_ROOT \
                    -x MASTER_ADDR=$MASTER_ADDR \
                    -x MASTER_PORT=$MASTER_PORT \
                    -x PYTHONPATH \
                    -x PT_HPU_LAZY_MODE=1 \
                    $CMD;


    Worker:
      replicas: 2
      template:
        spec:
          serviceAccountName: yourusername
          volumes:
            - name: mydir
              hostPath:
                path: /home/yourusername/test_mpi/pytorch
                type: Directory
            - name: scratch
              emptyDir: {}
          hostIPC: true
          containers:
            - image: vault.habana.ai/gaudi-docker/1.15.1/ubuntu22.04/habanalabs/pytorch-installer-2.2.0:latest
              name: test-worker
              imagePullPolicy: Always
              resources:
                limits:
                  habana.ai/gaudi: 8
                  cpu: 95
                  memory: 409Gi
                  hugepages-2Mi: 95000Mi
                requests:
                  habana.ai/gaudi: 8
                  cpu: 95
                  memory: 409Gi
                  hugepages-2Mi: 95000Mi
              volumeMounts:
                - name: mydir
                  mountPath: /mydir
                - name: scratch
                  mountPath: /scratch
 
