apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: yourusername-googlenet-8cards
  namespace: default
spec:
  slotsPerWorker: 8
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          volumes:
            - name: mydir
              hostPath:
                path: /home/yourusername
                type: Directory
            - name: scratch
              emptyDir: {}
            - name: ceph
              hostPath:
                path: /voyager/ceph/users/yourusername
                type: Directory
          hostIPC: true
          containers:
            - image: vault.habana.ai/gaudi-docker/1.13.0/ubuntu22.04/habanalabs/pytorch-installer-2.1.0:latest 
              name: googlenet-launcher
              volumeMounts:
                - name: mydir
                  mountPath: /home
                - name: scratch
                  mountPath: /scratch
                - name: ceph
                  mountPath: /ceph
              env:
                - name: dataset
                  value: "/ceph/datasets/imagenet/ILSVRC2012"
                - name: output
                  value: "/ceph/results/resnet/googlenet/8cards"
              command: ["/bin/bash", "-c"]
              args:
                - >-
                  declare -xr NUM_NODES=1;
                  declare -xr NGPU_PER_NODE=8;
                  declare -xr N_CARDS=$((NUM_NODES*NGPU_PER_NODE));

                  declare -xr SYNAPSE_AI_VER=1.13.0;

                  declare -xr RUN_PATH=/home/models/voyager/resnet/1.13.0/8cards;
                  declare -xr MODEL_PATH=/scratch/Model-References/PyTorch/computer_vision/classification/torchvision;

                  declare -xr PYTHONPATH=$PYTHONPATH:/scratch/Model-References;

                  HOSTSFILE=${HOSTSFILE:-$OMPI_MCA_orte_default_hostfile};
                  declare -xr MASTER_ADDR=$(head -n 1 $HOSTSFILE | sed -n s/[[:space:]]slots.*//p);
                  declare -xr MASTER_PORT=${MASTER_PORT:-15566};

                  echo $MASTER_ADDR;
                  echo $MASTER_PORT;

                  sleep 20s;

                  mpirun  --npernode 1 \
                    --tag-output \
                    --allow-run-as-root \
                    --prefix $MPI_ROOT \
                    -x MODEL_PATH \
                    -x SYNAPSE_AI_VER \
                    $RUN_PATH/setup.sh;

                  declare -xr CMD="python3 $MODEL_PATH/main.py \
                                   --data-path=${dataset} \
                                   --model=googlenet \
                                   --device=hpu \
                                   --batch-size=256 \
                                   --epochs=1 \
                                   --lr=0.2828 \
                                   --enable-lazy \
                                   --print-interval=20 \
                                   --dl-worker-type=HABANA \
                                   --seed=123 \
                                   --no-aux-logits \
                                   --autocast  \
                                   --workers=8";

                  
                  mpirun -np ${N_CARDS} \
                    --allow-run-as-root \
                    --bind-to core \
                    --map-by ppr:4:socket:PE=6 \
                    -rank-by core --report-bindings \
                    --tag-output \
                    --merge-stderr-to-stdout --prefix $MPI_ROOT \
                    -x MASTER_ADDR=$MASTER_ADDR \
                    -x MASTER_PORT=$MASTER_PORT \
                    -x PYTHONPATH \
                    $CMD;

                  mv checkpoint*.tar model*.tar ${output};

    Worker:
      replicas: 1
      template:
        spec:
          volumes:
            - name: mydir
              hostPath:
                path: /home/yourusername
                type: Directory
            - name: scratch
              emptyDir: {}
            - name: ceph
              hostPath:
                path: /voyager/ceph/users/yourusername
                type: Directory
          hostIPC: true
          containers:
            - image: vault.habana.ai/gaudi-docker/1.13.0/ubuntu22.04/habanalabs/pytorch-installer-2.1.0:latest 
              name: googlenet-worker
              imagePullPolicy: Always
              resources:
                limits:
                  habana.ai/gaudi: 8
                  cpu: 95
                  memory: 409Gi
                  hugepages-2Mi: 95000Mi
                requests:
                  habana.ai/gaudi: 8
                  cpu: 95
                  memory: 409Gi
                  hugepages-2Mi: 95000Mi
              volumeMounts:
                - name: mydir
                  mountPath: /home
                - name: scratch
                  mountPath: /scratch
                - name: ceph
                  mountPath: /ceph
 
